# Xception

In [1]:
import densenet

from keras.optimizers import RMSprop
from keras import regularizers
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D
from keras import backend as K
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras.callbacks import TensorBoard
from keras.applications.xception import Xception

Using TensorFlow backend.


In [2]:
import os, sys
current_dir = os.getcwd()
LESSON_HOME_DIR = current_dir
DATA_HOME_DIR = current_dir+'/data/'
train_data_dir = DATA_HOME_DIR+'train'

In [3]:
import numpy as np
np.random.seed(2016)

import os
import glob
import cv2
import math
import pickle
import datetime
import pandas as pd

from sklearn.cross_validation import train_test_split
from keras.utils import np_utils
from keras.models import model_from_json
from sklearn.metrics import log_loss

/home/paperspace/anaconda2/envs/tensorflow/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
def split_validation_set(train, target, test_size):
    random_state = 51
    X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

In [5]:
def split_validation_set_with_hold_out(train, target, test_size):
    random_state = 51
    train, X_test, target, y_test = train_test_split(train, target, test_size=test_size, random_state=random_state)
    X_train, X_holdout, y_train, y_holdout = train_test_split(train, target, test_size=test_size, random_state=random_state)
    return X_train, X_test, X_holdout, y_train, y_test, y_holdout

# Another approach to loading the data

In [6]:
from PIL import ImageFilter, ImageStat, Image, ImageDraw
from multiprocessing import Pool, cpu_count
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
import glob
import cv2

In [7]:
def im_multi(path):
    try:
        im_stats_im_ = Image.open(path)
        return [path, {'size': im_stats_im_.size}]
    except:
        print(path)
        return [path, {'size': [0,0]}]

def im_stats(im_stats_df):
    im_stats_d = {}
    p = Pool(cpu_count())
    ret = p.map(im_multi, im_stats_df['path'])
    for i in range(len(ret)):
        im_stats_d[ret[i][0]] = ret[i][1]
    im_stats_df['size'] = im_stats_df['path'].map(lambda x: ' '.join(str(s) for s in im_stats_d[x]['size']))
    return im_stats_df

def get_im_cv2(path):
    img = cv2.imread(path)
    resized = cv2.resize(img, (32, 32), cv2.INTER_LINEAR) #use cv2.resize(img, (64, 64), cv2.INTER_LINEAR)
    return [path, resized]

def normalize_image_features(paths):
    imf_d = {}
    p = Pool(cpu_count())
    ret = p.map(get_im_cv2, paths)
    for i in range(len(ret)):
        imf_d[ret[i][0]] = ret[i][1]
    ret = []
    fdata = [imf_d[f] for f in paths]
    fdata = np.array(fdata, dtype=np.uint8)
    fdata = fdata.transpose((0, 3, 1, 2))
    fdata = fdata.astype('float32')
    fdata = fdata / 255
    return fdata

In [8]:
train = glob.glob('data/train/**/*.jpg')# + glob.glob('../input/additional/**/*.jpg')

In [9]:
train[1]

'data/train/Type_3/1127.jpg'

In [10]:
train[1].split('/')

['data', 'train', 'Type_3', '1127.jpg']

In [11]:
train = pd.DataFrame([[p.split('/')[2],p.split('/')[3],p] for p in train], columns = ['type','image','path'])#[::5] #limit for Kaggle Demo

In [12]:
train = im_stats(train)
train = train[train['size'] != '0 0'].reset_index(drop=True) #remove bad images
train_data = normalize_image_features(train['path'])
np.save('train.npy', train_data, allow_pickle=True, fix_imports=True)

In [30]:
le = LabelEncoder()
train_target = le.fit_transform(train['type'].values)
train_target = np_utils.to_categorical(train_target, num_classes=3)

In [32]:
print(train_target[:5])

[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]


In [31]:
print(le.classes_) #in case not 1 to 3 order
np.save('train_target.npy', train_target, allow_pickle=True, fix_imports=True)

['Type_1' 'Type_2' 'Type_3']


Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (1480, 3, 32, 32) (32 channels).

In [33]:
print(train_data.shape)

(1480, 3, 32, 32)


In [34]:
train_data_channels_last = np.transpose(train_data, (0, 2, 3, 1))
# see: https://stackoverflow.com/a/23944468/6941138

In [35]:
print(train_data_channels_last.shape)

(1480, 32, 32, 3)


## Splitting the data

In [36]:
X_train, X_val, Y_train, Y_val = split_validation_set(train_data_channels_last, train_target, 0.1)

In [37]:
print(X_train.shape)

(1332, 32, 32, 3)


# Now building the model

In [38]:
def printTrainableLayers(model):
    for i, layer in enumerate(model.layers):
       if layer.trainable == True: 
           print(i, layer.name)

In [39]:
def printAllLayers(model):
    for i, layer in enumerate(model.layers):
       print(i, layer.name)

In [40]:
base_model = Xception(weights='imagenet', include_top=False)

In [41]:
# add a global spatial average pooling layer
x = base_model.output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
x = Dense(1024, activation='relu', kernel_initializer='glorot_uniform')(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu', kernel_initializer='glorot_uniform')(x)
# and a logistic layer -- let's say we have 200 classes
x = Dropout(0.5)(x)
predictions = Dense(3, activation='softmax', kernel_initializer='glorot_uniform')(x)

In [42]:
# this is the model we will train
model = Model(inputs=base_model.input, outputs=predictions)

In [21]:
printAllLayers(model)

(0, 'input_1')
(1, 'block1_conv1')
(2, 'block1_conv1_bn')
(3, 'block1_conv1_act')
(4, 'block1_conv2')
(5, 'block1_conv2_bn')
(6, 'block1_conv2_act')
(7, 'block2_sepconv1')
(8, 'block2_sepconv1_bn')
(9, 'block2_sepconv2_act')
(10, 'block2_sepconv2')
(11, 'block2_sepconv2_bn')
(12, 'conv2d_1')
(13, 'block2_pool')
(14, 'batch_normalization_1')
(15, 'add_1')
(16, 'block3_sepconv1_act')
(17, 'block3_sepconv1')
(18, 'block3_sepconv1_bn')
(19, 'block3_sepconv2_act')
(20, 'block3_sepconv2')
(21, 'block3_sepconv2_bn')
(22, 'conv2d_2')
(23, 'block3_pool')
(24, 'batch_normalization_2')
(25, 'add_2')
(26, 'block4_sepconv1_act')
(27, 'block4_sepconv1')
(28, 'block4_sepconv1_bn')
(29, 'block4_sepconv2_act')
(30, 'block4_sepconv2')
(31, 'block4_sepconv2_bn')
(32, 'conv2d_3')
(33, 'block4_pool')
(34, 'batch_normalization_3')
(35, 'add_3')
(36, 'block5_sepconv1_act')
(37, 'block5_sepconv1')
(38, 'block5_sepconv1_bn')
(39, 'block5_sepconv2_act')
(40, 'block5_sepconv2')
(41, 'block5_sepconv2_bn')
(42, 'b

In [43]:
# set the first 310 layers (up to the last conv block)
# to non-trainable (weights will not be updated)
for layer in model.layers[:132]:
    layer.trainable = False

In [44]:
printTrainableLayers(model)

(132, 'global_average_pooling2d_2')
(133, 'dense_4')
(134, 'dropout_3')
(135, 'dense_5')
(136, 'dropout_4')
(137, 'dense_6')


In [45]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_2 (InputLayer)             (None, None, None, 3) 0                                            
____________________________________________________________________________________________________
block1_conv1 (Conv2D)            (None, None, None, 32 864         input_2[0][0]                    
____________________________________________________________________________________________________
block1_conv1_bn (BatchNormalizat (None, None, None, 32 128         block1_conv1[0][0]               
____________________________________________________________________________________________________
block1_conv1_act (Activation)    (None, None, None, 32 0           block1_conv1_bn[0][0]            
___________________________________________________________________________________________

In [46]:
filepath="Xception-top-improvement_learning_rate_decy_0.01-{epoch:02d}-{val_loss:}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]
tbCallBack = TensorBoard(log_dir='./graph_xcep_top', histogram_freq=0, write_graph=True, write_images=True)
callbacks_list.append(tbCallBack)

In [47]:
opt = RMSprop(lr=1e-2, rho=0.9, decay=0.01)
#opt = SGD(lr=1e-2, momentum=0.9, decay=0.01, nesterov=True)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [48]:
batch_size = 16
nb_classes = 3
nb_epoch = 120
nb_train_samples = X_train.shape[0]
nb_val_samples = X_val.shape[0]

In [49]:
datagen = ImageDataGenerator(
        width_shift_range=0.2,
        height_shift_range=0.2,
        zoom_range=0.2,
        fill_mode='nearest')
datagen.fit(train_data_channels_last)

In [50]:
train_generator = datagen.flow(X_train,Y_train)

Sample hat shape: (32,32,32,3)

In [51]:
history = model.fit_generator(
        train_generator,
        steps_per_epoch=nb_train_samples // batch_size,
        epochs=nb_epoch,
        validation_data=(X_val, Y_val),
        validation_steps=nb_val_samples // batch_size,
        callbacks=callbacks_list)

Epoch 1/120
83/83 [==============================] - 6s - loss: 2.6412 - categorical_accuracy: 0.4765 - val_loss: 1.4723 - val_categorical_accuracy: 0.3514
Epoch 2/120
83/83 [==============================] - 3s - loss: 1.6998 - categorical_accuracy: 0.4905 - val_loss: 0.9940 - val_categorical_accuracy: 0.5541
Epoch 3/120
83/83 [==============================] - 2s - loss: 1.1015 - categorical_accuracy: 0.5047 - val_loss: 1.0022 - val_categorical_accuracy: 0.5541
Epoch 4/120
83/83 [==============================] - 2s - loss: 1.0559 - categorical_accuracy: 0.5127 - val_loss: 0.9993 - val_categorical_accuracy: 0.5541
Epoch 5/120
83/83 [==============================] - 2s - loss: 1.0428 - categorical_accuracy: 0.5185 - val_loss: 0.9984 - val_categorical_accuracy: 0.5541
Epoch 6/120
83/83 [==============================] - 2s - loss: 1.0323 - categorical_accuracy: 0.5186 - val_loss: 1.0065 - val_categorical_accuracy: 0.5541
Epoch 7/120
83/83 [==============================] - 3s - loss: 

83/83 [==============================] - 2s - loss: 1.0111 - categorical_accuracy: 0.5266 - val_loss: 0.9860 - val_categorical_accuracy: 0.5541
Epoch 27/120
83/83 [==============================] - 2s - loss: 1.0099 - categorical_accuracy: 0.5132 - val_loss: 1.0034 - val_categorical_accuracy: 0.5541
Epoch 28/120
83/83 [==============================] - 2s - loss: 0.9975 - categorical_accuracy: 0.5343 - val_loss: 0.9905 - val_categorical_accuracy: 0.5541
Epoch 29/120
83/83 [==============================] - 2s - loss: 1.0077 - categorical_accuracy: 0.5244 - val_loss: 0.9879 - val_categorical_accuracy: 0.5541
Epoch 30/120
83/83 [==============================] - 2s - loss: 1.0054 - categorical_accuracy: 0.5151 - val_loss: 0.9889 - val_categorical_accuracy: 0.5541
Epoch 31/120
83/83 [==============================] - 2s - loss: 1.0144 - categorical_accuracy: 0.5214 - val_loss: 0.9960 - val_categorical_accuracy: 0.5541
Epoch 32/120
83/83 [==============================] - 2s - loss: 1.0041

83/83 [==============================] - 2s - loss: 1.0067 - categorical_accuracy: 0.5198 - val_loss: 1.0222 - val_categorical_accuracy: 0.5541
Epoch 55/120
83/83 [==============================] - 2s - loss: 1.0085 - categorical_accuracy: 0.5227 - val_loss: 1.0058 - val_categorical_accuracy: 0.5541
Epoch 56/120
83/83 [==============================] - 2s - loss: 1.0024 - categorical_accuracy: 0.5306 - val_loss: 0.9955 - val_categorical_accuracy: 0.5541
Epoch 57/120
83/83 [==============================] - 2s - loss: 1.0006 - categorical_accuracy: 0.5244 - val_loss: 1.0104 - val_categorical_accuracy: 0.5541
Epoch 58/120
83/83 [==============================] - 2s - loss: 1.0165 - categorical_accuracy: 0.5250 - val_loss: 0.9923 - val_categorical_accuracy: 0.5541
Epoch 59/120
83/83 [==============================] - 2s - loss: 1.0088 - categorical_accuracy: 0.5217 - val_loss: 0.9921 - val_categorical_accuracy: 0.5541
Epoch 60/120
83/83 [==============================] - 2s - loss: 1.0105

83/83 [==============================] - 2s - loss: 1.0040 - categorical_accuracy: 0.5249 - val_loss: 0.9928 - val_categorical_accuracy: 0.5541
Epoch 83/120
83/83 [==============================] - 2s - loss: 1.0013 - categorical_accuracy: 0.5243 - val_loss: 0.9897 - val_categorical_accuracy: 0.5541
Epoch 84/120
83/83 [==============================] - 2s - loss: 1.0069 - categorical_accuracy: 0.5251 - val_loss: 0.9902 - val_categorical_accuracy: 0.5541
Epoch 85/120
83/83 [==============================] - 2s - loss: 0.9992 - categorical_accuracy: 0.5275 - val_loss: 0.9947 - val_categorical_accuracy: 0.5541
Epoch 86/120
83/83 [==============================] - 2s - loss: 1.0116 - categorical_accuracy: 0.5191 - val_loss: 0.9864 - val_categorical_accuracy: 0.5541
Epoch 87/120
83/83 [==============================] - 2s - loss: 0.9991 - categorical_accuracy: 0.5220 - val_loss: 0.9949 - val_categorical_accuracy: 0.5541
Epoch 88/120
83/83 [==============================] - 2s - loss: 0.9986

83/83 [==============================] - 2s - loss: 0.9986 - categorical_accuracy: 0.5243 - val_loss: 0.9940 - val_categorical_accuracy: 0.5541
Epoch 110/120
83/83 [==============================] - 2s - loss: 1.0012 - categorical_accuracy: 0.5213 - val_loss: 1.0026 - val_categorical_accuracy: 0.5541
Epoch 111/120
83/83 [==============================] - 2s - loss: 1.0071 - categorical_accuracy: 0.5325 - val_loss: 1.0001 - val_categorical_accuracy: 0.5541
Epoch 112/120
83/83 [==============================] - 2s - loss: 1.0136 - categorical_accuracy: 0.5136 - val_loss: 0.9994 - val_categorical_accuracy: 0.5541
Epoch 113/120
83/83 [==============================] - 2s - loss: 0.9999 - categorical_accuracy: 0.5236 - val_loss: 0.9856 - val_categorical_accuracy: 0.5541
Epoch 114/120
83/83 [==============================] - 2s - loss: 1.0131 - categorical_accuracy: 0.5247 - val_loss: 1.0174 - val_categorical_accuracy: 0.5541
Epoch 115/120
83/83 [==============================] - 2s - loss: 

In [52]:
# serialize model to JSON
model_json = model.to_json()
with open("xcep_top_only.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("xcep_top_only.h5")
print("Saved model to disk")

Saved model to disk


# Submit to kaggle for testing purposes

## Loading test data

In [53]:
test = glob.glob('data/test/**/*.jpg')
test = pd.DataFrame([[p.split('/')[3],p] for p in test], columns = ['image','path']) #[::20] #limit for Kaggle Demo
test_data = normalize_image_features(test['path'])
np.save('test.npy', test_data, allow_pickle=True, fix_imports=True)

test_id = test.image.values
np.save('test_id.npy', test_id, allow_pickle=True, fix_imports=True)

In [55]:
print(test_data.shape)

(512, 3, 32, 32)


In [56]:
test_data_channels_last = np.transpose(test_data, (0, 2, 3, 1))

In [57]:
print(test_data_channels_last.shape)

(512, 32, 32, 3)


In [59]:
# Calculate class posteriors probabilities
y_probabilities = model.predict(test_data_channels_last, batch_size=16, verbose=0)
print(len(y_probabilities))

512


In [60]:
print(y_probabilities[:5])

[[ 0.17143506  0.51594162  0.31262332]
 [ 0.17145009  0.51688492  0.31166497]
 [ 0.13735089  0.47895184  0.38369721]
 [ 0.1652036   0.50534153  0.32945487]
 [ 0.17166527  0.51636571  0.31196898]]


In [61]:
df = pd.DataFrame(y_probabilities, columns=['Type_1','Type_2','Type_3'])
df['image_name'] = test_id
df.to_csv('submission.csv', index=False)

In [62]:
%ls

data/
Data_Exploration.ipynb
densenet.py
densenet.pyc
good_run/
graph_xcep_top/
InceptionV3.ipynb
models/
results/
Simple Starter.ipynb
submission.csv
test_id.npy
test.npy
train.npy
train_target.npy
Xception.ipynb
Xception-top-improvement-00-7.84123565055.hdf5
Xception-top-improvement_learning_rate_decy_0.01-00-1.47230166358.hdf5
Xception-top-improvement_learning_rate_decy_0.01-01-0.993979115744.hdf5
Xception-top-improvement_learning_rate_decy_0.01-06-0.993341072186.hdf5
Xception-top-improvement_learning_rate_decy_0.01-07-0.989474592982.hdf5
Xception-top-improvement_learning_rate_decy_0.01-10-0.986634248012.hdf5
Xception-top-improvement_learning_rate_decy_0.01-14-0.985346645922.hdf5
Xception-top-improvement_learning_rate_decy_0.01-15-0.98243128609.hdf5
Xception-top-improvement_learning_rate_decy_0.01-17-0.981213746844.hdf5
Xception-top-improvement_learning_rate_decy_0.01-88-0.980523177095.hdf5
Xception-top-improvement_learning_rate_decy_0.01-89-0.976933294051.hdf5
xcep_top_only.h5
xcep

ERROR:root:Line magic function `%kg` not found.
